builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
  binary: kube2pulumi
  main: ./cmd/kube2pulumi/main.go
archives:
  - name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
brews:
  - 
    name: kube2pulumi
    github:
      owner: pulumi
      name: homebrew-tap
    commit_author:
      name: pulumi-bot
      email: bot@pulumi.com
    homepage: "https://pulumi.io"
    description: "Convert Kubernetes manifests to Pulumi code"
